### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by tabletguy** [spongebobrf/BookdashAndroidApp#3]
I downloaded the project (zip) and opened the project main folder with Android Studio 2.0 Beta 2 (I think). 

Would like to be able to build and "step through/debug" things to learn from it.

After quite a while, it gave this error message:

Error:Execution failed for task ':app:processMockDebugGoogleServices'.
> File google-services.json is missing from module root folder. The Google Services Plugin cannot function without it.

---------

On the Gradle Sync tab were these messages. Note that I have all the project source at the E drive location listed. I believe I have all Android Studio settings correctly configured.

--------
Source folders generated at incorrect location
Warning:Folder E:\Downloads\Android Development\BookdashAndroidApp-master\app\build\data-binding-info\mock\debug
Warning:Folder E:\Downloads\Android Development\BookdashAndroidApp-master\app\build\data-binding-info\androidTest\mock\debug
Information:3rd-party Gradle plug-ins may be the cause

**Comment by spongebobrf** [comment]
Hi tabletguy
Go generate a google-services.json file by following the instructions here: 
https://developers.google.com/mobile/add?platform=android You will need to select App Invites API and Google Analytics and enter your SHA-1 of your debug keystore.

This is in the setup guide :)

**Comment by tabletguy** [comment]
I had actually read that setup guide, but didn't realize I needed to actually do that before it would compile. I thought I could just compile and run locally without that stuff. Sorry!

The setup guide doesn't say what name I should use for the Google App name?  Should it be "BookdashAndroidApp" or something unique to myself such as "GloriouslyWithoutAClueApp"?

Simlarly, for running local only (in the development environment) do I also need the fabric.io account?

Thanks for your patience and time.

(Sorry about the large bold text in first message!)

**Comment by spongebobrf** [comment]
You can call it anything you want for the Google App name. 

You should be okay without a fabric account for development. I have disabled it for debug builds in the Application object.
` Crashlytics crashlyticsKit = new Crashlytics.Builder()
                .core(new CrashlyticsCore.Builder().disabled(BuildConfig.DEBUG).build())
                .build();
        Fabric.with(this, crashlyticsKit);`
